version: '3'

tasks:
  development:
    dir: 'opentofu/development'
    cmds:
      - infisical run --path="/terraform" -- {{.CLI_ARGS}}

  proxies:
    dir: 'opentofu/proxies'
    cmds:
      - infisical run --path="/terraform" -- {{.CLI_ARGS}}
