name: CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  changes:
    name: Determine
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      infrastructure: ${{ steps.filter.outputs.infrastructure }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - '.github/workflows/cd.yml'
              - 'frontend/**'
            infrastructure:
              - '.github/workflows/cd.yml'
              - 'infrastructure/opentofu/**'

  infrastructure:
    name: Apply OpenTofu infrastructure
    runs-on: ubuntu-latest

    needs: [changes]
    if: ${{ needs.changes.outputs.infrastructure == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.8
        with:
          client-id: ${{ vars.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: '${{ vars.INFISICAL_PROJECT_SLUG }}'
          env-slug: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          secret-path: '/terraform'

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.0

      - name: Initialize OpenTofu
        run: tofu init
        working-directory: infrastructure/opentofu/${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
        env:
          ARM_SAS_TOKEN: ${{ env.ARM_SAS_TOKEN }}

  frontend:
    name: Lint, build and deploy frontend
    runs-on: ubuntu-latest

    needs: [changes, infrastructure]
    if: ${{ needs.changes.outputs.frontend == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.8
        with:
          client-id: ${{ vars.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: '${{ vars.INFISICAL_PROJECT_SLUG }}'
          env-slug: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          secret-path: '/frontend'

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('/bun.lock') }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: frontend

      - name: Run linter
        run: bun frontend lint
        working-directory: frontend

      - name: Build project
        run: bun frontend build
        working-directory: frontend

      - name: Deploy Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'frontend/application/dist'
          skip_app_build: true
