name: CI Pipeline

on:
  workflow_dispatch:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  changes:
    name: Determine
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            frontend:
              - '.github/workflows/ci.yml'
              - 'frontend/**'

  frontend:
    name: Lint and build frontend
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('/bun.lock') }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: frontend

      - name: Run linter
        run: bun frontend lint
        working-directory: frontend

      - name: Build project
        run: bun frontend build
        working-directory: frontend
